  0%|                                                                                                                         | 0/40000 [00:00<?, ?it/s]Could not estimate the number of tokens of the input, floating-point operations will not be computed
  0%|                                                                                                              | 1/40000 [00:06<72:15:16,  6.50s/it]Traceback (most recent call last):
  File "/home/daniel/RFM/projects/gr00t/run_finetune.py", line 116, in <module>
    main()
  File "/home/daniel/RFM/projects/gr00t/run_finetune.py", line 112, in main
    experiment.train()
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/experiment/runner.py", line 173, in train
    self.trainer.train(resume_from_checkpoint=self.resume_from_checkpoint)
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/experiment/trainer.py", line 153, in train
    return super().train(resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 2514, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches, args.device)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 5243, in get_batch_samples
    batch_samples.append(next(epoch_iterator))
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/accelerate/data_loader.py", line 563, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
    return self._process_data(data)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 8.
Original Traceback (most recent call last):
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/data/dataset.py", line 508, in __getitem__
    return self.transforms(self.get_step_data(trajectory_id, base_index))
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/data/dataset.py", line 539, in get_step_data
    for modality in self.modality_keys:
RuntimeError: dictionary changed size during iteration

Traceback (most recent call last):
  File "/home/daniel/RFM/projects/gr00t/run_finetune.py", line 116, in <module>
    main()
  File "/home/daniel/RFM/projects/gr00t/run_finetune.py", line 112, in main
    experiment.train()
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/experiment/runner.py", line 173, in train
    self.trainer.train(resume_from_checkpoint=self.resume_from_checkpoint)
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/experiment/trainer.py", line 153, in train
    return super().train(resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 2514, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches, args.device)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/transformers/trainer.py", line 5243, in get_batch_samples
    batch_samples.append(next(epoch_iterator))
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/accelerate/data_loader.py", line 563, in __iter__
    next_batch = next(dataloader_iter)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1445, in _next_data
    return self._process_data(data)
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 8.
Original Traceback (most recent call last):
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/daniel/anaconda3/envs/gr00t/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/data/dataset.py", line 508, in __getitem__
    return self.transforms(self.get_step_data(trajectory_id, base_index))
  File "/home/daniel/RFM/Isaac-GR00T/gr00t/data/dataset.py", line 539, in get_step_data
    for modality in self.modality_keys:
RuntimeError: dictionary changed size during iteration
